name: getting started
on:
  workflow_dispatch:
  push:
    branches: 
      - main

jobs:
  setupNode:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: test
      LOG_LEVEL: debug
    steps:
      - name: print env
        run: |
          echo "Environment: ${{env.NODE_ENV}}
          echo "Log level: ${{env.LOG_LEVEL}}
      - name: checkout
        uses: actions/checkout@v6.1.0
      
      - name: install Node.js 22
        uses: actions/setup-node@v6.5.0
        with:
          node-version: 22

      - name: run npm install 
        run: npm install

      - name: npm test
        run: npm test
      
       
       
    
