name: gym's workflow

on:
  push:
    branches:
      - main
      - "releases/**"

jobs:
  build_docker_image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
      name: Check out code

      uses: mr-smithers-excellent/docker-build-push@v6
      with:
        image: raissianouer/gym-website
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}