name: gym's workflow

on:
  push:
    branches:
      - main
      - "releases/**"

jobs:
  build_docker_image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v5

      - name: build docker image
        run: docker build -t gym_website:latest .
