name: my workflow

on:
  push:
    branches:
      - main
      - "releases/**"

jobs:
  build_docker_image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          token: ${{secrets.GITHUB_TOKEN}}

      - name: build docker image
        run: docker build -t gym-website:latest .

      - name: confirmation
        run: "echo image built successfully"
